# site domain
site_domain: https://www.manomano.fr

# slug of the section to scrape.
# you can easily change the section to scrape by just changing this value.
# tested on other section like 'spa-gonflable-2874'
section_slug: perceuse-1146


# using https://www:manomano:fr/perceuse-1146?page=2:, the slug is 'page'
page_slug: page


# List of pages to visit. use a list like [2,3] for the second and third page.
# You can also use [-1] to scrape many successive subpages  of the section.

pages_list: [-1]

# Maximum number of next pages. Used only for other_pages = [-1]
max_number_pages: 3

#next page link selector. Useful only for other_pages = [-1]
next_page: ul.pagination_00689b92

# div of products layout
page_main_div: div.ProductsLayout_root__1bT-H.Products_root__3L0a7.ListingLayout_products__NwzPC

# selector of single product
single_product_layout:  a.root_11bb9625

# elements out of single_product_info_div
product_more_info:
  url:
    css: a
    type: attr(href)

  brand:
    css: img.brand_a1bc186a
    type: attr(alt)

# div containing all the most of the information on product
single_product_info_div: div.contentContainer_11bb9625
product_info:
  title:
    css: div.root_fda1b303.title_11bb9625.root_6af7768f.body2_6af7768f.semiBold_6af7768f.primaryDark_6af7768f
    type: text

  price_integer:
    css: span.root_2f0f2a85.euro_2f0f2a85.root_5489989d.main_14117adf span.integer_2f0f2a85
    type: text

  price_decimal:
    css: span.root_2f0f2a85.euro_2f0f2a85.root_5489989d.main_14117adf sup span.decimal_2f0f2a85
    type: text

  no_discount_price_integer:
    css: span.root_2f0f2a85.euro_2f0f2a85.root_c90c837f.retail_c90c837f.retail_14117adf span.integer_2f0f2a85
    type: text

  no_discount_price_decimal:
    css: span.root_2f0f2a85.euro_2f0f2a85.root_c90c837f.retail_c90c837f.retail_14117adf span.decimal_2f0f2a85
    type: text

  rating:
    css: span.stars_8392a9ff
    type: attr(aria-label)

  number_of_ratings:
    css: div.root_8392a9ff div.root_6af7768f.small_6af7768f.regular_6af7768f.primaryDark_6af7768f
    type: text